import type {Metadata} from 'next'
import localFont from 'next/font/local'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist',
  weight: '100 200 300 400 500 600 700 800 900',
})

export const metadata: Metadata = {
  title: 'Korostelev',
  description: 'Generated by create next app',
}

import Header from '~/Global/Header'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className="scroll-smooth" lang="ru">
      <body className={`${geistSans.variable} font-sans antialiased text-foreground !bg-foreground`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
