import type {Metadata} from 'next'
import localFont from 'next/font/local'
import './globals.css'

const Geist = localFont({
  src: [
    {
      path: '../assets/fonts/Geist-ExtraLight.woff2',
      weight: '200',
    },
    {
      path: '../assets/fonts/Geist-Light.woff2',
      weight: '300',
    },
    {
      path: '../assets/fonts/Geist-Regular.woff2',
      weight: '400',
    },
    {
      path: '../assets/fonts/Geist-Medium.woff2',
      weight: '500',
    },
    {
      path: '../assets/fonts/Geist-SemiBold.woff2',
      weight: '600',
    },
    {
      path: '../assets/fonts/Geist-Bold.woff2',
      weight: '700',
    },
  ],
  variable: '--font-geist',
})

export const metadata: Metadata = {
  title: 'Korostelev',
  description: 'Generated by create next app',
}

import Notification from '~/UI/Notification'
import Loader from '~/Global/Loader'
import Header from '~/Global/Header'
import YandexMetrika from '~/Global/Analytics'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className="scroll-smooth" lang="ru">
      <body className={`${Geist.variable} font-sans antialiased text-foreground !bg-foreground`}>
        {process.env.NODE_ENV === 'production' && <Loader />}
        <Notification />
        <Header />
        {children}
      </body>

      {process.env.NODE_ENV === 'production' && <YandexMetrika />}
    </html>
  )
}
